# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0.json
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      day: monday
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(deps): update"
      prefix-development: "chore(deps-dev): update"
      include: scope
    groups:
      github-actions:
        patterns:
          - "*"
    rebase-strategy: auto
    allow:
      - dependency-type: direct
      - dependency-type: indirect

  - package-ecosystem: mix
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "mix"
    commit-message:
      prefix: "chore(deps): update"
      prefix-development: "chore(deps-dev): update"
      include: scope
    groups:
      elixir-deps:
        patterns:
          - "*"
    versioning-strategy: auto
    allow:
      - dependency-type: direct
      - dependency-type: indirect
