version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(deps): update"
      prefix-development: "chore(deps-dev): update"
      include: "scope"
    groups:
      github-actions:
        patterns:
          - "*"
    rebase-strategy: "auto"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"

  - package-ecosystem: "hex"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "hex"
    commit-message:
      prefix: "chore(deps): update"
      prefix-development: "chore(deps-dev): update"
      include: "scope"
    groups:
      elixir-deps:
        patterns:
          - "*"
    versioning-strategy: "auto"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
